### ISSUE TITLE
Ruby 2.5 - @@after_run.reverse_each exception after upgrade from 2.4

### ISSUE THREAD

**Issue by alessio-signorini** [seattlerb/minitest#758]
After upgrading from Ruby 2.4.4 to 2.5.1 I started receiving a strange `minitest` error while running my Rails test

````bash
Traceback (most recent call last):
/home/ec2-user/.rvm/gems/ruby-2.5.0/bin/bundle: undefined method `reverse_each' for nil:NilClass (NoMethodError)
````
Which I traced it back to [this line](https://github.com/seattlerb/minitest/blob/master/lib/minitest.rb#L59) using a debugger.

Here is a minimal test that generates the error (`test_helper.rb` is emtpy)

````ruby
ENV["RAILS_ENV"] = "test"

require File.expand_path('../../config/environment', __FILE__)

require 'minitest/autorun'

class TestMeme < ActiveSupport::TestCase

  test 'fail' do
    assert false
  end
end
````

Here is the full output of my console

````bash
$ bundle exec rake test test/empty_test.rb 
Run options: --seed 43379

# Running:

F

Finished in 0.002320s, 431.0835 runs/s, 431.0835 assertions/s.
Traceback (most recent call last):
/home/ec2-user/.rvm/gems/ruby-2.5.0/bin/bundle: undefined method `reverse_each' for nil:NilClass (NoMethodError)
````

Instead of showing details on the errors it bails out with that line. Reverting back to ruby-2.4.4 resolve the issue.

Do you guys know what it may be causing it?

**Comment by alessio-signorini** [comment]
This was caused by the `better_errors` gem. Upgrading to `v2.5.0` does not resolve the issue. I eliminated the gem from my Gemfile's test section.

**Comment by zenspider** [comment]
Can you elaborate on what better_errors was doing or provide a reproduction?
