### ISSUE TITLE
must_match raises NoMethodError: undefined method `assert_match` for nil::NilClass

### ISSUE THREAD

**Issue by veeg** [seattlerb/minitest#651]
## Synopsis

Using `must_match` maps to an `assert_match` call invoked on a NilClass context.
### Environment

``` bash
$> gem list | grep minitest
minitest (5.9.1)
$> ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
```

This was working in Minitest 4.7.5 and ruby 2.1. Bug discovered when I ran my testsuite after upgrading my Linux installation.
## Test program

``` ruby
require 'minitest/autorun'

class LolTest < Minitest::Test
  def test_lol
    string = "lol"
    string.must_match "lol"
  end
end
```
## Running test result

``` bash
$> ruby -d lol.rb
Exception `LoadError' at /usr/share/rubygems/rubygems.rb:1250 - cannot load such file -- rubygems/defaults/ruby
Exception `LoadError' at /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55 - cannot load such file -- did_you_mean
Exception `LoadError' at /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55 - cannot load such file -- abrt
Exception `LoadError' at /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:132 - cannot load such file -- abrt
Exception `LoadError' at /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55 - cannot load such file -- minitest/autorun
Run options: --seed 50507

# Running:

Exception `NoMethodError' at /home/vegardsa/.gem/ruby/gems/minitest-5.9.1/lib/minitest/spec.rb:23 - undefined method `assert_match' for nil:NilClass
E

Finished in 0.003106s, 321.9466 runs/s, 0.0000 assertions/s.

  1) Error:
LolTest#test_lol:
NoMethodError: undefined method `assert_match' for nil:NilClass
    /home/vegardsa/.gem/ruby/gems/minitest-5.9.1/lib/minitest/spec.rb:23:in `must_match'
    /home/vegardsa/.gem/ruby/gems/minitest-5.9.1/lib/minitest/spec.rb:11:in `must_match'
    lol.rb:6:in `test_lol'
    /home/vegardsa/.gem/ruby/gems/minitest-5.9.1/lib/minitest/test.rb:107:in `block (3 levels) in run'
    /home/vegardsa/.gem/ruby/gems/minitest-5.9.1/lib/minitest/test.rb:204:in `capture_exceptions'
    /home/vegardsa/.gem/ruby/gems/minitest-5.9.1/lib/minitest/test.rb:104:in `block (2 levels) in run'
    /home/vegardsa/.gem/ruby/gems/minitest-5.9.1/lib/minitest/test.rb:255:in `time_it'
    /home/vegardsa/.gem/ruby/gems/minitest-5.9.1/lib/minitest/test.rb:103:in `block in run'
    /home/vegardsa/.gem/ruby/gems/minitest-5.9.1/lib/minitest.rb:348:in `on_signal'
    /home/vegardsa/.gem/ruby/gems/minitest-5.9.1/lib/minitest/test.rb:275:in `with_info_handler'
    /home/vegardsa/.gem/ruby/gems/minitest-5.9.1/lib/minitest/test.rb:102:in `run'
    /home/vegardsa/.gem/ruby/gems/minitest-5.9.1/lib/minitest.rb:799:in `run_one_method'
    /home/vegardsa/.gem/ruby/gems/minitest-5.9.1/lib/minitest.rb:322:in `run_one_method'
    /home/vegardsa/.gem/ruby/gems/minitest-5.9.1/lib/minitest.rb:310:in `block (2 levels) in run'
    /home/vegardsa/.gem/ruby/gems/minitest-5.9.1/lib/minitest.rb:309:in `each'
    /home/vegardsa/.gem/ruby/gems/minitest-5.9.1/lib/minitest.rb:309:in `block in run'
    /home/vegardsa/.gem/ruby/gems/minitest-5.9.1/lib/minitest.rb:348:in `on_signal'
    /home/vegardsa/.gem/ruby/gems/minitest-5.9.1/lib/minitest.rb:335:in `with_info_handler'
    /home/vegardsa/.gem/ruby/gems/minitest-5.9.1/lib/minitest.rb:308:in `run'
    /home/vegardsa/.gem/ruby/gems/minitest-5.9.1/lib/minitest.rb:158:in `block in __run'
    /home/vegardsa/.gem/ruby/gems/minitest-5.9.1/lib/minitest.rb:158:in `map'
    /home/vegardsa/.gem/ruby/gems/minitest-5.9.1/lib/minitest.rb:158:in `__run'
    /home/vegardsa/.gem/ruby/gems/minitest-5.9.1/lib/minitest.rb:135:in `run'
    /home/vegardsa/.gem/ruby/gems/minitest-5.9.1/lib/minitest.rb:62:in `block in autorun'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips

```

**Comment by utilum** [comment]
I see the same error, and keep seeing it after switching to Minitest 4.7.5 and ruby 2.1.3p242.

**Comment by zenspider** [comment]
@utilum did it work in previous versions??

**Comment by zenspider** [comment]
@veeg you want to use classes and methods but with expectations? That's a new one... 😄 

If you change your superclass to `Minitest::Spec`, it works fine:

```ruby
class LolTest < Minitest::Spec
  def test_lol
    string = "lol"
    string.must_match "lol"
  end
end
```

```
# Running:

.

Finished in 0.002126s, 470.3669 runs/s, 940.7338 assertions/s.

1 runs, 2 assertions, 0 failures, 0 errors, 0 skips
```

You should start using `_`/`value`/`expect` to wrap the LHS tho...

**Comment by utilum** [comment]
@zenspider as this appears to be a user mistake, no need to continue drilling down versions history, is there?

**Comment by zenspider** [comment]
@utilum just wanted to know if this was a backwards incompatibility.

**Comment by veeg** [comment]
I've done some more investigations in regard to environment and such. I may have provided slight false information before. The environment I (most likely ran) was Minitest 5.8.1, not 4.7.5. I had a colleague test with his setup on our testsuite:
```
minitest: 5.8.1
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux-gnu]
```
The tests pass.

```
minitest: 5.8.1 and 5.9.1
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
```
Test does not pass.

## More realistic test
```ruby
require 'minitest/autorun'

class ParameterTest < Minitest::Test
  def test_parameter
    err = assert_raises RuntimeError do
      raise "Parameter not fulfilled"
    end
    err.message.must_match(/Parameter not fulfilled/)
  end
end
```

So the difference seem to stem from different ruby versions (2.1 to 2.3).

@zenspider Change this to Subclass Minitest::Spec and it works on ruby 2.3. I suppose the reason I've used to subclass Test is because of my several lack of understanding about the difference. Most of my inspiration for writing my unit tests has been through google searches on minitest usage. Could you clarify the difference between Test and Spec and the difference scenarios these should be used?

**Comment by utilum** [comment]
Minitest::Test is more direct and closer to 'pure' Ruby code. Minitest::Spec accepts a more 'story' like syntax, often associated with 'Behavior-Driven-Development', then translates it, behind the scenes. If you are not particularly motivated to adopt either approach... you don't have to. But sticking to one until you are motivated to try another would help you avoid splice failures like the one above.

**Comment by veeg** [comment]
I must say, I've only ever really just looked at the API available and called the methods that suit me the most. I've never made a conscious decision about one over the other. However, I don't particularly favor the behavior-driven syntax, which is why I've ended up in this situation.

Do you have any recommendations on how to match the exception message while sticking to subclassing Test?  (Since its obviously not working too well for me right now..)

**Comment by utilum** [comment]
how about `assert_equal 'lol', my_var` ?

**Comment by veeg** [comment]
Hmm. Can't use Regexp to match then.

**Comment by utilum** [comment]
@veeg, have you read the documentation?

**Comment by veeg** [comment]
```ruby
require 'minitest/autorun'

class ParameterTest < Minitest::Test
  def test_parameter
    err = assert_raises RuntimeError do
      raise "Parameter not fulfilled"
    end
    assert_match /Parameter/, err.message
  end
end
```

This works. Oh well. Thank you for your time anyway.

I would still classify this difference between ruby 2.1 and ruby 2.3 as a bug, even though
you may rule my usage of your API a user-error.

**Comment by utilum** [comment]
I could not reproduce your error with Ruby 2.1, and you did not use the API, you took a method from one API and called it on another, which resulted in a NoMethodError.

**Comment by veeg** [comment]
I did not get the same error in ruby 2.1, see the updated testcase.

I would say that the difference in API is not very well documented/dummy proofed.
My simply googling different cases and looking at different API calls, most of my development has been by trying and failing. When it worked, I (wrongly) assumed that everything was OK.

I would suggest adding an exception to all methods from Minitest::Excepectations check that parent modules include Minitest::Spec. That would have forced me to do it correctly from the get-go.

**Comment by zenspider** [comment]
@veeg I'm confused by your report. You say that _something_ doesn't work in ruby 2.3 but does work in ruby 2.2? I can't tell what that is at this point. At this point, it'd help me tremendously if you'd please show your work with actual code.

I did this with the original, the `assert_match` version, and the `Spec` + `must_match` version:

```bash
for VER in 5.8.1 5.9.1 ; do
  for RUBY in ruby22 ruby23 ; do
    echo $RUBY $VER
    eval $RUBY -I../$VER/lib bug651.rb
  done
done
```

And it gives me 100% consensus (either all passing or all failing) on all versions of your tests above. Version of ruby and version of minitest should not matter. Minitest is too clean and ruby doesn't differ that much from 2.2 to 2.3 to matter. If the code is correct for the API, it passes, and if it is not correct, it fails.

If you want to use expectations, please use `describe` or subclass `Minitest::Spec` (which what `describe` basically does). If you want to use assertions, well, you can use either `Minitest::Test`, `describe`, or `Minitest::Spec`.

> I would say that the difference in API is not very well documented/dummy proofed.

Please point out specific examples where the API is not well documented and I will do my best to address it.

There are many copies of minitest documentation, please cite your source so I know what you're referencing.

**Comment by zenspider** [comment]
@veeg ... anything?

**Comment by veeg** [comment]
Sorry, I totally forgot about this.

I'm unfortunately unable to reproduce the environment (my old installation) where my unit tests passed. I've since tried to reproduce the error on both 2.1 and 2.3 version of Ruby, but to no avail. I do not know what was so special about the setup I had that made it work, but I'll conclude for myself that I was simply using the API wrong.
